general_settings:
  max_retries: 2
  timeout: 120

model_list:
  - model_name: "qwen3-14b:free"
    litellm_params:
      model: "openrouter/qwen/qwen3-14b:free"
      api_base: "https://openrouter.ai/api/v1"
      api_key: os.environ/OPENROUTER_API_KEY
      extra_headers:
        HTTP-Referer: os.environ/OPENROUTER_SITE_URL
        X-Title:      os.environ/OPENROUTER_APP_NAME

  - model_name: "gpt-oss-120b:free"
    litellm_params:
      model: "openrouter/openai/gpt-oss-120b:free"
      api_base: "https://openrouter.ai/api/v1"
      api_key: os.environ/OPENROUTER_API_KEY

  # 🚨 CHANGED: route ALL OpenAI models natively (not via OpenRouter)
  - model_name: "openai/*"
    litellm_params:
      model: "openai/*"                         # LiteLLM’s native OpenAI provider
      api_base: "https://api.openai.com/v1"     # native OpenAI endpoint
      api_key: os.environ/OPENAI_API_KEY        # your OpenAI key

router_settings:
  timeout: 120
  num_retries: 2
